# -*- coding: utf-8 -*-
"""atm code

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ORgBQI1zu2cq-79xmtGqSIiXPaDv9iNY
"""

class bank:
    check_balance=500
    exit="Exit"
    def print_check_balance(self):
      print(bank.check_balance)

obj=bank()
print(obj.print_check_balance())

class bank:
    check_balance=500
    exit="Exit"
    def __init__(self,withdraw,deposite):
        self.withdraw=withdraw
        self.deposite=deposite
    def print_withdraw(self):
        print(self.check_balance-self.withdraw)
    def print_deposite(self):
        print(self.check_balance+self.deposite)
    def print_exit(self):
        print(bank.exit)


obj=bank(300,200)
obj.print_withdraw()
obj.print_deposite()
obj.print_exit()