# -*- coding: utf-8 -*-
"""dictionaries.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y7nIHyP2DWhP6jzvyQY4Km7uf4l_7W6t
"""

n=15
if ((n%3)==0) and ((n%5)==0):
  print("fizzbuzz")
elif (n%3)==0:
  print("buzz")
elif n%5==0:
  print("fuzz")
else:
  print(n)

def more_args(arg='hi'):
    print(data)


data={'arg':'hello'}
more_args(data)

dict_a= {
'name':'teja',
'age':15
}
for k in dict_a.keys():
    if k == 'name':
        print(dict_a)

