# -*- coding: utf-8 -*-
"""f-string.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SlGeB0KoztUtk7Y_ZWgQ0vVjWLyV0Fso
"""

a=input()
b=int(input())
print(f"name is {a} and {b} years old")