# -*- coding: utf-8 -*-
"""If-Else conditions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pDEai30HU0sgZANnZ-iGSNIR3KAb5HEr
"""

n=int(input())
if n>5:
   b=(5/100)*n
  print(b+n)
else:
    print(n)

n=int(input())
if n<25:
  print("F")
elif n>=25 and n<=45:
  print("E")
elif n>45 and n<=50:
  print("D")
elif n>50 and n<=60:
  print("E")
elif n>70 and n<=80:
  print("D")
else:
  print("A")

a=int(input())
b=int(input())
if a==b:
  print("SQUARE")
else:
  print("NOT SQUARE")

a=int(input())
b=int(input())
if a>b:
  print(a)
else:
  print(b)

a=int(input())
if a>1000:
  b=(10/100)*a
  print(b+a)
else:
  print(a)