# -*- coding: utf-8 -*-
"""imp question.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G2P1Ggkgc_3uZ4Ba993hJdyUPfI73wMC
"""

print('True') if (6>2)

a=str(21)
sum=0
for i in (a):
    sum+=int(i)
if (int(a)%sum)==0:
    print("it is a hardad number")
else:
    print("it is not harsad number")

a=25
b=str((a**2))
m=len(b)
c=(b[-len(str(a)):])
if str(a)==c :
    print("automorphic numbar")
else:
    print("it is not automorphic numbar")



n = int(input('enter a number :- '))
sq = n ** 2
if str(n) == str(sq)[-len(str(n)):]:
  print('automorphic numbar')

else:
  print('not automorphic numbar')

from typing import ItemsView
a=dict([("saikumar",10),("ram",20)])
print(a)

