# -*- coding: utf-8 -*-
"""Oops.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lFI2kKyihAL8pnrwIwLHL-OHZzboo6Ni
"""

class mobile:
  def __init__(self,model,camera):
    self.model=model
    self.camera=camera
  def make_call(self,number):
    print("calling...{}".format(number))
a=mobile('samsung 5g',"50Mp")
print(id(a))
b=mobile("vivo","48Mp")
print(id(b))

